name: ci

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build
      run: cargo build
    - name: Test
      run: cargo test --all-features
    - name: Fmt
      run: cargo fmt -- --check
    - name: Clippy
      run: cargo clippy
